# Generated by Django 4.0.6 on 2022-08-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoryType',
            field=models.CharField(choices=[('NW', 'One String News'), ('AR', 'Articles'), ('REG', 'REG'), ('POL', 'POL')], default='AR', max_length=4),
        ),
    ]
