# Generated by Django 4.1.3 on 2022-12-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msitex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selfpr',
            options={'ordering': ['-title'], 'verbose_name': 'About my hobby and a bit `bout me', 'verbose_name_plural': 'About my hobby and a bit `bout me'},
        ),
        migrations.AlterField(
            model_name='selfpr',
            name='images',
            field=models.ImageField(blank=True, upload_to='upl/images/%Y/%m/%d', verbose_name='Photo'),
        ),
    ]
