# Generated by Django 4.0.6 on 2022-08-01 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_post_categorytype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='body',
        ),
    ]
